@php
$items = [
    [
        'name' => 'Dashboard',
        'route' => route('home'),
        'icon' => 'speedometer2',
        'img' => 'dashboard.webp',
        'active' => Route::is('home'),
        'is_blank' => false,
    ],
    [
        'name' => 'POS',
        'route' => route('pos.show'),
        'icon' => 'receipt',
        'img' => 'cashier.webp',
        'active' => Route::is('pos.show'),
        'is_blank' => false,
    ],
    [
        'name' => 'Orders',
        'route' => route('orders.index'),
        'icon' => 'card-list',
        'img' => 'inbox.webp',
        'active' => Route::is('orders.*'),
        'is_blank' => false,
    ],
    [
        'name' => 'Sales Report',
        'route' => route('sales.index'),
        'icon' => 'card-list',
        'img' => 'growth.webp',
        'active' => Route::is('sales.*'),
        'is_blank' => false,
    ],
    [
        'name' => 'Stock Management',
        'route' => route('stocks.index'),
        'icon' => 'card-list',
        'img' => 'shipping.webp',
        'active' => Route::is('stocks.*'),
        'is_blank' => false,
    ],
    [
        'name' => 'Inventory Items',
        'route' => route('master-items.index'),
        'icon' => 'card-list',
        'img' => 'cart.webp',
        'active' => Route::is('master-items.*'),
        'is_blank' => false,
    ],
    [
        'name' => 'Vendors',
        'route' => route('vendors.index'),
        'icon' => 'card-list',
        'img' => 'salesman.webp',
        'active' => Route::is('vendors.*'),
        'is_blank' => false,
    ],
    [
        'name' => 'Waste Management',
        'route' => route('wastes.index'),
        'icon' => 'card-list',
        'img' => 'trash.webp',
        'active' => Route::is('wastes.*'),
        'is_blank' => false,
    ],
    [
        'name' => 'Delivery Charge Report',
        'route' => route('delivery-charge.show'),
        'icon' => 'card-list',
        'img' => 'delivery.webp',
        'active' => Route::is('delivery.*'),
        'is_blank' => false,
    ],

    // [
    //     'name' => 'Categories',
    //     'route' => route('categories.index'),
    //     'icon' => 'card-list',
    //     'img' => 'square.webp',
    //     'active' => Route::is('categories.*'),
    //     'is_blank' => false,
    // ],
    // [
    //     'name' => 'Products',
    //     'route' => route('products.index'),
    //     'icon' => 'archive',
    //     'img' => 'box.webp',
    //     'active' => Route::is('products.*'),
    //     'is_blank' => false,
    // ],
    [
        'name' => 'Tables',
        'route' => route('tables.index'),
        'icon' => 'table',
        'img' => 'table.webp',
        'active' => Route::is('tables.*'),
        'is_blank' => false,
    ],
    [
        'name' => 'Customers',
        'route' => route('customers.index'),
        'icon' => 'archive',
        'img' => 'group.webp',
        'active' => Route::is('customers.*'),
        'is_blank' => false,
    ],
    [
        'name' => 'User Manager',
        'route' => route('users.index'),
        'icon' => 'archive',
        'img' => 'profile.webp',
        'active' => Route::is('users.*'),
        'is_blank' => false,
    ],
    [
        'name' => 'Settings',
        'route' => route('settings.show'),
        'icon' => 'gear',
        'img' => 'gear.webp',
        'active' => Route::is('settings.*'),
        'is_blank' => false,
    ],
    [
        'name' => 'About',
        'route' => route('about'),
        'icon' => 'gear',
        'img' => 'info.webp',
        'active' => Route::is('about.*'),
        'is_blank' => false,
    ],
];
@endphp
@include('layouts.sidebar')
